export const MANIFEST_VERSION = "1.0";

export const DEFAULT_SUPPORTED_EXTENSIONS = Object.freeze([
  ".mp3",
  ".wav",
  ".aif",
  ".aiff",
  ".flac",
  ".m4a"
]);

export const ERROR_CODES = Object.freeze({
  INVALID_INPUT: "INVALID_INPUT",
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  TARGET_NOT_ACCESSIBLE: "TARGET_NOT_ACCESSIBLE",
  METADATA_READ_FAILED: "METADATA_READ_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
});

export const IGNORE_REASONS = Object.freeze({
  UNSUPPORTED_EXTENSION: "UNSUPPORTED_EXTENSION",
  HIDDEN_FILE: "HIDDEN_FILE",
  DUPLICATED_PATH: "DUPLICATED_PATH",
  NOT_A_FILE: "NOT_A_FILE"
});
