/**
 * Todos los textos visibles de MusicKind en español.
 * Cero textos literales en JSX: siempre strings.xxx.
 */

export const strings = {
  app: {
    name: "MusicKind",
    tagline: "DJ Audio Suite",
  },
  common: {
    browse: "Examinar",
    cancel: "Cancelar",
    save: "Guardar",
    saved: "Guardado",
    delete: "Eliminar",
    add: "Agregar",
    pause: "Pausar",
    resume: "Reanudar",
    retry: "Reintentar",
    close: "Cerrar",
    search: "Buscar…",
    openFolder: "Abrir carpeta",
    showInFolder: "Mostrar en carpeta",
    openFile: "Abrir archivo",
    undo: "Deshacer",
    confirm: "Confirmar",
    settings: "Configuración",
    loading: "Cargando…",
    error: "Error en el proceso",
    simulateError: "Simular error",
    reset: "Restablecer",
    seconds: "s",
    bpm: "BPM",
    key: "Tonalidad",
    genre: "Género",
    track: "Pista",
    file: "Archivo",
    status: "Estado",
    actions: "Acciones",
    dryRun: "Simulación",
    dryRunTooltip: "Modo prueba: no mueve ni modifica archivos reales",
    confidence: "Confianza",
    completed: "Completado",
    inProgress: "En curso",
    idle: "Inactivo",
    paused: "Pausado",
    destination: "Destino",
    source: "Fuente",
  },
  nav: {
    classifier: "Clasificador",
    sets: "Sets",
    converter: "Convertidor",
    metadata: "Metadatos",
    bpm: "BPM",
    stems: "Stems",
    settings: "Configuración",
    collapseSidebar: "Colapsar barra lateral",
    expandSidebar: "Expandir barra lateral",
    commandPalette: "Paleta de comandos",
    systemStatus: "Estado del sistema",
  },
  command: {
    placeholder: "Escribe un comando o busca…",
    navigationGroup: "Vistas",
    actionsGroup: "Acciones rápidas",
    goToClassifier: "Ir a Clasificador",
    goToSets: "Ir a Sets",
    goToConverter: "Ir a Convertidor",
    goToMetadata: "Ir a Metadatos",
    goToBpm: "Ir a BPM y Tonalidad",
    goToStems: "Ir a Separación de Stems",
    goToSettings: "Ir a Configuración",
    checkDependencies: "Verificar dependencias",
    clearResults: "Limpiar resultados actuales",
    shortcutCmdK: "⌘K",
    noResults: "No se encontraron comandos.",
  },
  systemStatus: {
    title: "Estado del sistema",
    ready: "Listo",
    warning: "Advertencia",
    missing: "Faltante",
    ffmpeg: "FFmpeg",
    python: "Python / librosa",
    demucs: "Demucs (Stems)",
    ffmpegOk: "FFmpeg 6.1 instalado",
    pythonOk: "Python 3.11 con librosa activo",
    demucsOk: "Modelo v4 cargado (~2 GB)",
    ffmpegMissing: "FFmpeg no encontrado",
    pythonMissing: "Dependencias de análisis pendientes",
    demucsMissing: "Modelo de stems sin descargar",
    openSettings: "Abrir dependencias",
  },
  classifier: {
    title: "Clasificador",
    emptyDrop: "Soltar carpeta",
    selectedFolder: "Carpeta de música",
    dryRunLabel: "Modo simulación",
    activeGenres: "Géneros activos",
    activeGenresButton: "Géneros",
    addGenrePlaceholder: "Nuevo género…",
    classify: "Clasificar",
    sortFiles: "Ordenar",
    undoSort: "Deshacer ordenamiento",
    reclassify: "Re-clasificar",
    tableTrack: "Pista",
    tableBpm: "BPM",
    tableKey: "Key",
    tableGenre: "Género detectado",
    tableSource: "Fuente",
    tableDest: "Carpeta destino",
    missingKeysTitle: "Faltan credenciales de Spotify",
    missingKeysAction: "Ir a Configuración",
    toastSorted: "Archivos organizados con éxito",
    toastUndone: "Se revirtió el ordenamiento de archivos",
    toastSavedGenres: "Lista de géneros guardada",
    toastStarted: "Iniciando clasificación por género…",
    toastCanceled: "Clasificación cancelada",
    toastError: "Fallo durante la clasificación",
    inspectorFolder: "Carpeta destino",
    inspectorOriginalFile: "Archivo de origen",
    inspectorSource: "Fuente de detección",
    genreDistribution: "Distribución por género",
  },
  sets: {
    title: "Sets",
    emptyDrop: "Soltar carpetas de set",
    warmupFolder: "Warmup",
    peakFolder: "Peak",
    closingFolder: "Closing",
    newPackFolder: "Pack nuevo",
    secondsLabel: "Segundos de análisis",
    analyze: "Analizar",
    tableTrack: "Pista",
    tableBpm: "BPM",
    tableKey: "Key",
    tableSection: "Sección",
    tableWarmup: "Warmup",
    tablePeak: "Peak",
    tableClosing: "Closing",
    tableBestSection: "Mejor sección",
    energyCurveTitle: "Curva de energía del set",
    toastStarted: "Analizando energía para estructura de sets…",
    toastCompleted: "Análisis de sets finalizado",
    toastCanceled: "Análisis cancelado",
    energyAnalysis: "Desglose de energía",
    recommendationLabel: "Recomendación para set",
    warmupSectionHeader: "WARMUP",
    peakSectionHeader: "PEAK",
    closingSectionHeader: "CLOSING",
  },
  converter: {
    title: "Convertidor",
    emptyDrop: "Soltar archivos o carpeta",
    selectedInput: "Entrada seleccionada",
    formatLabel: "Formato destino",
    bitrateLabel: "Bitrate MP3",
    convert: "Convertir",
    tableFile: "Archivo",
    tableConversion: "Conversión",
    tableSize: "Tamaño",
    tableStatus: "Estado",
    tableActions: "Acciones",
    missingFfmpegTitle: "FFmpeg no disponible",
    missingFfmpegAction: "Ir a Configuración",
    toastStarted: "Iniciando conversión de audio…",
    toastCompleted: "Conversión de audio completada",
    toastCanceled: "Conversión cancelada",
    summaryFormat: "12 archivos · 486 MB → 1.2 GB",
    inspectorSpecs: "Especificaciones de audio",
    originalFormat: "Formato original",
    targetFormat: "Formato destino",
    outputPath: "Ruta de archivo",
  },
  metadata: {
    title: "Metadatos",
    emptyDrop: "Soltar archivos para auto-tag",
    selectedInput: "Archivos seleccionados",
    identify: "Identificar",
    tableFile: "Archivo",
    tableTrack: "Pista",
    tableAlbum: "Álbum",
    tableYear: "Año",
    tableConfidence: "Confianza",
    sheetTitle: "Editar metadatos ID3",
    sheetDescription: "Modifica etiquetas antes de escribir al archivo",
    fieldTitle: "Título",
    fieldArtist: "Artista",
    fieldAlbum: "Álbum",
    fieldYear: "Año",
    fieldGenre: "Género",
    fieldTrackNumber: "N.º de pista",
    fieldNewFileName: "Nombre de archivo nuevo",
    saveMetadata: "Guardar metadatos",
    toastStarted: "Identificando metadatos acústicos…",
    toastIdentified: "Metadatos identificados",
    toastUpdated: "Etiquetas guardadas con éxito",
    inspectorEditTitle: "Editor de etiquetas ID3",
    originalTag: "Original",
    newTag: "Nuevo valor",
  },
  bpm: {
    title: "BPM",
    emptyDrop: "Soltar archivos para BPM / Key",
    selectedInput: "Carpeta de análisis",
    secondsLabel: "Segundos de análisis",
    analyze: "Analizar",
    tableTrack: "Pista",
    tableBpm: "BPM",
    tableKey: "Key",
    tableActions: "Acciones",
    saveRow: "Guardar",
    savePendingChanges: "Guardar cambios pendientes",
    saveCountChanges: "Guardar {count} cambios",
    toastStarted: "Calculando BPM y detección armónica…",
    toastCompleted: "Análisis de BPM y tonalidad listo",
    toastRowSaved: "BPM y tonalidad actualizados",
    toastAllSaved: "Todos los cambios han sido guardados",
    inspectorBeatgrid: "Cuadrícula rítmica (Beatgrid)",
    originalBpmLabel: "BPM original",
    currentBpmLabel: "BPM editado",
    keyCorrection: "Corrección tonal",
  },
  stems: {
    title: "Stems",
    emptyDrop: "Soltar pista de audio",
    selectedFile: "Pista de entrada",
    formatLabel: "Formato de salida",
    separate: "Separar",
    vocalsCardTitle: "Voces",
    instrumentalCardTitle: "Instrumental",
    originalCardTitle: "Original",
    openStemFile: "Reproducir stem",
    showStemInFolder: "Mostrar en carpeta",
    toastStarted: "Separando voces e instrumentales con Demucs…",
    toastCompleted: "Separación de stems finalizada",
    toastCanceled: "Separación cancelada",
    dawMute: "M",
    dawSolo: "S",
    dawVolume: "Vol",
    dawPlay: "Reproducir",
    dawPause: "Pausar",
    dawTimeline: "Línea de tiempo",
  },
  settings: {
    title: "Configuración",
    navApiKeys: "API Keys",
    navLanguage: "Idioma",
    navOutput: "Carpeta de salida",
    navDependencies: "Dependencias",
    navAbout: "Acerca de",
    spotifyClientId: "Spotify Client ID",
    spotifyClientSecret: "Spotify Client Secret",
    lastFmKey: "Last.fm API Key",
    acoustIdKey: "AcoustID API Key",
    showSecret: "Mostrar clave",
    hideSecret: "Ocultar clave",
    languageSelect: "Idioma de la interfaz",
    languageSpanish: "Español",
    languageEnglish: "English",
    outputFolderLabel: "Ruta de salida unificada",
    selectFolder: "Seleccionar",
    depFfmpeg: "FFmpeg",
    depLibrosa: "Herramientas de audio librosa",
    depDemucs: "Separación de stems demucs (~2 GB)",
    depStatusOk: "Instalado y verificado",
    depStatusMissing: "No instalado",
    depVerify: "Verificar",
    depInstall: "Instalar",
    depVerifyAll: "Verificar todo",
    aboutAppName: "MusicKind Desktop",
    aboutVersion: "Versión 1.4.0 (Build Electron)",
    aboutEngine: "Motor de análisis armónico y clasificación para DJs",
    toastSettingsSaved: "Configuración guardada",
    toastVerifiedAll: "Todas las dependencias están verificadas",
    toastDepInstalled: "Dependencia instalada correctamente",
  },
} as const;
